stages:
    #   - lint
    # - test
    - build
    # - docker

# variables:
#   GO_VERSION: "1.22"
#   CGO_ENABLED: "0"
#   GOFLAGS: "-mod=readonly"
#   DOCKER_DRIVER: overlay2


image: golang:1.26
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - go/pkg/mod
        - .cache/go-build

before_script:
    - go env -w GOPROXY=https://repo.tibobit.ir/repository/golang/,direct
    - go version
    - go mod download



# lint:
#   stage: lint
#   image: golangci/golangci-lint:v1.56
#   script:
#     - golangci-lint run ./...
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#     - if: $CI_COMMIT_BRANCH

# test:
#     stage: test
#     variables:
#         CGO_ENABLED: 1
#     script:
#         - go test -v -race -cover ./...
#     # artifacts:
#     #     reports:
#     #         junit: report.xml
#     coverage: '/coverage: \d+\.\d+%/'
#     rules:
#         - if: $CI_COMMIT_BRANCH

build:
  stage: build
  script:
    - go build -ldflags="-s -w" -o main ./cmd/main
  artifacts:
    paths:
      - main
    # expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH

# docker-build:
#   stage: docker
#   image: docker:25
#   services:
#     - docker:25-dind
#   variables:
#     DOCKER_TLS_CERTDIR: ""
#   before_script:
#     - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
#   script:
#     - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
#     - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
#     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
#     - docker push $CI_REGISTRY_IMAGE:latest
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
