FROM alpine:3.22

WORKDIR /app

# Create non-root user for security
RUN addgroup -g 1001 -S appgroup && \
    adduser -u 1001 -S appuser -G appgroup

COPY main ./main
COPY .env.example .env

# Change ownership to non-root user
RUN chown appuser:appgroup main


# Switch to non-root user
USER appuser

EXPOSE 8080

# Set the default command to run the application
ENTRYPOINT ["./main", "serve"]
