apiVersion: v1
data:
  KAFKA_PASSWORD: ""
  KAFKA_USERNAME: ""
  POSTGRES_PASSWORD: MXFheiFRQVo=
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: "2026-02-10T20:24:09Z"
  name: challenge-test-service-secrets
  namespace: default
type: Opaque
