// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	"context"
	"control-panel-service/internal/domain/entity"

	"github.com/stretchr/testify/mock"
)

type FactorialRepository struct {
	mock.Mock
}

func (m *FactorialRepository) Create(ctx context.Context, factorial *entity.Factorial) error {
	args := m.Called(ctx, factorial)
	return args.Error(0)
}
