apiVersion: v1
kind: Secret
metadata:
  name: ${IMAGE_NAME}-secrets
type: Opaque
stringData:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  KAFKA_HOST: "${KAFKA_HOST}"
  KAFKA_PORT: "${KAFKA_PORT}"
  KAFKA_USERNAME: "${KAFKA_USERNAME}"
  KAFKA_PASSWORD: "${KAFKA_PASSWORD}"
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_SSL_MODE: "${POSTGRES_SSL_MODE}"
  OTLP_GRPC_HOST: "${OTLP_GRPC_HOST}"
  OTLP_GRPC_PORT: "${OTLP_GRPC_PORT}"
  SWAGGER_HOST: ${SWAGGER_HOST}
