services:
    control-panel-service:
        image: challenge-control-panel-service:TAG_NAME
        container_name: challenge-control-panel-service
        restart: unless-stopped
        ports:
            - "8080:8080"
        env_file:
            - ../.env
        networks:
            - backend

    control-panel-jobs-service:
        image: challenge-control-panel-service:TAG_NAME
        container_name: challenge-control-panel-jobs-service
        restart: unless-stopped
        env_file:
            - ../.env
        entrypoint: ["./main", "jobs"]
        networks:
            - backend

networks:
    backend:
        external: true
