// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/mother-services": {
            "post": {
                "description": "Create a new mother service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mother-services"
                ],
                "summary": "Create a mother service",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.MotherService"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/mother-services/search": {
            "post": {
                "description": "Get mother services with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mother-services"
                ],
                "summary": "Get paginated mother services",
                "parameters": [
                    {
                        "description": "Pagination request with page and per_page",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PaginationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PaginatedMotherServices"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/mother-services/{id}": {
            "get": {
                "description": "Retrieve a specific mother service by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mother-services"
                ],
                "summary": "Get mother service by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Mother service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MotherServiceResponseByID"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/mother-services/{id}/delete": {
            "post": {
                "description": "Delete a specific mother service by its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mother-services"
                ],
                "summary": "Delete a mother service.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Test scenario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test-categories": {
            "get": {
                "description": "Retrieve all available test categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-categories"
                ],
                "summary": "Get all test categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.TestCategory"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test-categories/{id}": {
            "get": {
                "description": "Retrieve a specific test category by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-categories"
                ],
                "summary": "Get test category by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Test category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.TestCategory"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test-scenarios": {
            "post": {
                "description": "Create a new test scenario with configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-scenarios"
                ],
                "summary": "Create a test scenario",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.TestScenario"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test-scenarios/search": {
            "post": {
                "description": "Get test scenarios with pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-scenarios"
                ],
                "summary": "Get paginated test scenarios",
                "parameters": [
                    {
                        "description": "Pagination request with page and per_page",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.TestScenarioPaginationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PaginatedTestScenario"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test-scenarios/update": {
            "post": {
                "description": "Update test scenario with configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-scenarios"
                ],
                "summary": "Update a test scenario",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.TestScenarioUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test-scenarios/{id}": {
            "get": {
                "description": "Retrieve a specific test scenario by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-scenarios"
                ],
                "summary": "Get test scenario by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Test scenario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.TestScenarioResponseByID"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test-scenarios/{id}/delete": {
            "post": {
                "description": "Delete a specific test scenario by its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-scenarios"
                ],
                "summary": "Delete a test scenario.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Test scenario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test-scenarios/{id}/pause": {
            "post": {
                "description": "Retrieve a specific test scenario by its ID and pause the scenario.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-scenarios"
                ],
                "summary": "Pause a test scenario.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Test scenario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test-scenarios/{id}/resume": {
            "post": {
                "description": "Retrieve a specific test scenario by its ID and resume the scenario.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-scenarios"
                ],
                "summary": "Resume a test scenario.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Test scenario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test-scenarios/{id}/start": {
            "post": {
                "description": "Retrieve a specific test scenario by its ID and start the scenario.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-scenarios"
                ],
                "summary": "Start a test scenario.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Test scenario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test-scenarios/{id}/stop": {
            "post": {
                "description": "Stop a specific test scenario by its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-scenarios"
                ],
                "summary": "Stop a test scenario.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Test scenario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/control-panel-service_internal_server_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "control-panel-service_internal_server_dto_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "entity.MotherServiceStatus": {
            "type": "string",
            "enum": [
                "ready",
                "running",
                "paused",
                "stopped",
                "deleted",
                "failed"
            ],
            "x-enum-comments": {
                "MotherServiceStatusDeleted": "stop and delete containers. can not start again.",
                "MotherServiceStatusFailed": "provisioning permanently failed after retries",
                "MotherServiceStatusPaused": "application level pause on sending request",
                "MotherServiceStatusReady": "mother service just created",
                "MotherServiceStatusRunning": "test is running on application level (sending level)",
                "MotherServiceStatusStopped": "stop container but can start scenario again."
            },
            "x-enum-descriptions": [
                "mother service just created",
                "test is running on application level (sending level)",
                "application level pause on sending request",
                "stop container but can start scenario again.",
                "stop and delete containers. can not start again.",
                "provisioning permanently failed after retries"
            ],
            "x-enum-varnames": [
                "MotherServiceStatusReady",
                "MotherServiceStatusRunning",
                "MotherServiceStatusPaused",
                "MotherServiceStatusStopped",
                "MotherServiceStatusDeleted",
                "MotherServiceStatusFailed"
            ]
        },
        "entity.ScenarioStatus": {
            "type": "string",
            "enum": [
                "ready",
                "pending",
                "running",
                "paused",
                "stopped",
                "deleted",
                "succeed"
            ],
            "x-enum-varnames": [
                "ScenarioStatusReady",
                "ScenarioStatusPending",
                "ScenarioStatusRunning",
                "ScenarioStatusPaused",
                "ScenarioStatusStopped",
                "ScenarioStatusDeleted",
                "ScenarioStatusSucceed"
            ]
        },
        "request.MotherService": {
            "type": "object",
            "properties": {
                "database_name": {
                    "type": "string"
                },
                "database_table_name": {
                    "type": "string"
                },
                "exception_rate": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "random_response_delay_max": {
                    "type": "integer"
                },
                "random_response_delay_min": {
                    "type": "integer"
                },
                "response_delay_duration": {
                    "type": "integer"
                },
                "response_delay_rate": {
                    "type": "integer"
                }
            }
        },
        "request.PaginationRequest": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                }
            }
        },
        "request.TestScenario": {
            "type": "object",
            "properties": {
                "execution_number_multi_agent": {
                    "type": "integer"
                },
                "increase_agent_number": {
                    "type": "integer"
                },
                "max_test_service_count": {
                    "type": "integer"
                },
                "mother_service_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "num_steps": {
                    "type": "integer"
                },
                "test_category_id": {
                    "type": "integer"
                },
                "test_service_config": {
                    "$ref": "#/definitions/request.TestServiceConfigRequest"
                }
            }
        },
        "request.TestScenarioPaginationRequest": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                }
            }
        },
        "request.TestScenarioUpdateRequest": {
            "type": "object",
            "properties": {
                "execution_number_multi_agent": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "increase_agent_number": {
                    "type": "integer"
                },
                "max_test_service_count": {
                    "type": "integer"
                },
                "mother_service_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "num_steps": {
                    "type": "integer"
                },
                "test_service_config": {
                    "$ref": "#/definitions/request.TestServiceConfigRequest"
                }
            }
        },
        "request.TestServiceConfigRequest": {
            "type": "object",
            "properties": {
                "bad_value_rate": {
                    "type": "integer"
                },
                "database_name": {
                    "type": "string"
                },
                "database_table_name": {
                    "type": "string"
                },
                "execution_number_multi_fixed_input": {
                    "type": "integer"
                },
                "fixed_test_number": {
                    "type": "integer"
                },
                "increase_fixed_input": {
                    "type": "integer"
                },
                "long_string_value_rate": {
                    "type": "integer"
                },
                "max_duration": {
                    "type": "integer"
                },
                "max_requests": {
                    "type": "integer"
                },
                "negative_value_rate": {
                    "type": "integer"
                },
                "null_value_rate": {
                    "type": "integer"
                },
                "random_request_delay_max": {
                    "type": "integer"
                },
                "random_request_delay_min": {
                    "type": "integer"
                },
                "random_test_number_max": {
                    "type": "integer"
                },
                "random_test_number_min": {
                    "type": "integer"
                },
                "real_value_rate": {
                    "type": "integer"
                },
                "request_delay_duration": {
                    "type": "integer"
                },
                "string_value_rate": {
                    "type": "integer"
                },
                "zero_value_rate": {
                    "type": "integer"
                }
            }
        },
        "response.MotherService": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "database_name": {
                    "type": "string"
                },
                "database_table_name": {
                    "type": "string"
                },
                "exception_rate": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "random_response_delay_max": {
                    "type": "integer"
                },
                "random_response_delay_min": {
                    "type": "integer"
                },
                "response_delay_duration": {
                    "type": "integer"
                },
                "response_delay_rate": {
                    "type": "integer"
                },
                "service_deployment_address": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/entity.MotherServiceStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.MotherServiceResponseByID": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.MotherService"
                }
            }
        },
        "response.PaginatedMotherServices": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MotherService"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.PaginatedTestScenario": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TestScenario"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "response.TestCategory": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "has_max_test_service_count": {
                    "type": "boolean"
                },
                "has_num_steps": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.TestScenario": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "editable": {
                    "type": "boolean"
                },
                "execution_number_multi_agent": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "increase_agent_number": {
                    "type": "integer"
                },
                "max_test_service_count": {
                    "type": "integer"
                },
                "mother_service": {
                    "$ref": "#/definitions/response.MotherService"
                },
                "name": {
                    "type": "string"
                },
                "num_steps": {
                    "type": "integer"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/entity.ScenarioStatus"
                },
                "test_category": {
                    "$ref": "#/definitions/response.TestCategory"
                },
                "test_service_config": {
                    "$ref": "#/definitions/response.TestServiceConfig"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.TestScenarioResponseByID": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.TestScenario"
                }
            }
        },
        "response.TestServiceConfig": {
            "type": "object",
            "properties": {
                "bad_value_rate": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "database_name": {
                    "type": "string"
                },
                "database_table_name": {
                    "type": "string"
                },
                "execution_number_multi_fixed_input": {
                    "type": "integer"
                },
                "fixed_test_number": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "increase_fixed_input": {
                    "type": "integer"
                },
                "long_string_value_rate": {
                    "type": "integer"
                },
                "max_duration": {
                    "type": "integer"
                },
                "max_requests": {
                    "type": "integer"
                },
                "negative_value_rate": {
                    "type": "integer"
                },
                "null_value_rate": {
                    "type": "integer"
                },
                "random_request_delay_max": {
                    "type": "integer"
                },
                "random_request_delay_min": {
                    "type": "integer"
                },
                "random_test_number_max": {
                    "type": "integer"
                },
                "random_test_number_min": {
                    "type": "integer"
                },
                "real_value_rate": {
                    "type": "integer"
                },
                "request_delay_duration": {
                    "type": "integer"
                },
                "string_value_rate": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "zero_value_rate": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
