package pkg

import (
	"errors"
)

var (
	ErrInternalServerError             = errors.New("internal server error")
	ErrFailedToSendEventData           = errors.New("failed to send event data")
	ErrFailedToConsumeData             = errors.New("failed to consume data")
	ErrFailedToUnmarshalEventData      = errors.New("failed to unmarshal factorial event")
	ErrFailedToLoadConfig              = errors.New("failed to load config from env")
	ErrFailedToCreateMotherService     = errors.New("failed to create mother service item")
	ErrMotherServiceNotFound           = errors.New("mother service not found")
	ErrFailedToGetMotherService        = errors.New("failed to get mother service instance")
	ErrFailedToGetMotherServices       = errors.New("failed to get mother service instances")
	ErrMotherServiceAlreadyExist       = errors.New("mother service already exist")
	ErrNegativePageOrPerPageNotAllowed = errors.New("negative value for page or per page are not allowed")
	ErrTestScenarioNotFound            = errors.New("test scenario not found")
	ErrFailedToGetTestScenario         = errors.New("failed to get test scenario")
	ErrFailedToGetTestScenarios        = errors.New("failed to get test scenarios")
	ErrFailedToCreateTestScenario      = errors.New("failed to create test scenario")
	ErrTestCategoryNotFound            = errors.New("test category not found")
	ErrFailedToGetTestCategory         = errors.New("failed to get test category record")
	ErrFailedToValidateTestSvcCfg      = errors.New("failed to validate test service config data")

	// Validation errors.
	ErrInvalidName                             = errors.New("mother service name is required")
	ErrInvalidExceptionRate                    = errors.New("exception rate must be between 0 and 100")
	ErrInvalidResponseDelayRate                = errors.New("response delay rate must be between 0 and 100")
	ErrInvalidDelayConfiguration               = errors.New("invalid delay configuration: must be either no delay, fixed delay, or random delay")
	ErrInvalidRandomDelayRange                 = errors.New("random delay min must be less than max")
	ErrInvalidDatabaseName                     = errors.New("database name is required")
	ErrInvalidDatabaseTableName                = errors.New("database table name is required")
	ErrInvalidKafkaLivefeedTopic               = errors.New("kafka livefeed topic is required")
	ErrInvalidKafkaFactorialTopic              = errors.New("kafka factorial topic is required")
	ErrFailedToGetTestCategoriesFromRepository = errors.New("failed to get test categories from repository")
	ErrFailedToGetTestCategoryFromRepository   = errors.New("failed to get test category from repository")
	ErrExecutionDurationLessThanOne            = errors.New("execution duration should be more than one")
	ErrMaxTestServiceCountLessThanOne          = errors.New("max test service count should be more than 1")
	ErrAutoStepChangeRateLessThanOne           = errors.New("auto step change rate should be more than one")
	ErrMaxTestServiceCountNotSet               = errors.New("for this test scenario max test service count should be set")
	ErrNoNeedMaxTestServiceCount               = errors.New("no need to set max service count")
	ErrExecutionDurationNotSet                 = errors.New("for this test scenario execution duration should be set")
	ErrNoNeedExecutionDuration                 = errors.New("no need to set execution duration")
	ErrAutoStepChangeNotSet                    = errors.New("for this test scenario auto step change should be set")
	ErrNoNeedAutoStepChange                    = errors.New("no need to set auto step change rate")
	ErrFailedToSendProvisioningEvent           = errors.New("failed to send provisioning event")
	ErrInvalidMaxRequest                       = errors.New("invalid max request number, couldn't be negative")
	ErrInvalidMaxDuration                      = errors.New("invalid max duration time, couldn't be negative")
	ErrInvalidRequestDelayDuration             = errors.New("invalid request delay duration")
	ErrInvalidRequestDelayDurationConfig       = errors.New("invalid request delay duration configuration")
	ErrMinDelayDurationMoreThanMax             = errors.New("min request random delay duration not be more than max request delay duration")
	ErrInvalidFixedTestNumber                  = errors.New("fixed test number couldn't be negative")
	ErrInvalidFixedTestNumberConfig            = errors.New("invalid fixed test number configuration")
	ErrMinRandomTestNumberMoreThanMax          = errors.New("min random test number couldn't be more than max random test number")
	ErrInvalidMinOrMaxRandomTestNumber         = errors.New("min random test number or max random test number couldn't be negative")
	ErrInvalidBadValueRate                     = errors.New("bad value rate should be between 0 and 100")
	ErrInvalidNegativeValueRate                = errors.New("negative value rate should be between 0 and 100")
	ErrInvalidRealValueRate                    = errors.New("real value rate should be between 0 and 100")
	ErrInvalidZeroValueRate                    = errors.New("zero value rate should be between 0 and 100")
	ErrInvalidStringValueRate                  = errors.New("string value rate should be between 0 and 100")
	ErrInvalidLongStringValueRate              = errors.New("long string value rate should be between 0 and 100")
	ErrInvalidNullValueRate                    = errors.New("null value rate should be between 0 and 100")
)
